# Generated by Django 5.1.1 on 2024-09-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('notable_offspring', models.TextField(blank=True, null=True)),
                ('wife', models.CharField(blank=True, max_length=255, null=True)),
                ('lifespan', models.IntegerField(blank=True, null=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rabbis.person')),
            ],
        ),
        migrations.CreateModel(
            name='SpousalRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husbands', to='rabbis.person')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wives', to='rabbis.person')),
            ],
        ),
    ]
