# Generated by Django 5.1.1 on 2024-09-29 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='person',
            name='notable_offspring',
        ),
        migrations.AlterField(
            model_name='person',
            name='wife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='husbands', to='rabbis.person'),
        ),
        migrations.DeleteModel(
            name='SpousalRelationship',
        ),
        migrations.AddField(
            model_name='person',
            name='notable_offspring',
            field=models.ManyToManyField(blank=True, related_name='parents', to='rabbis.person'),
        ),
    ]
