# Generated by Django 5.1.1 on 2024-09-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='notable_offspring',
        ),
        migrations.RemoveField(
            model_name='person',
            name='wife',
        ),
        migrations.AddField(
            model_name='person',
            name='notable_offspring',
            field=models.ManyToManyField(blank=True, related_name='parents', to='rabbis.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='wife',
            field=models.ManyToManyField(blank=True, related_name='husbands', to='rabbis.person'),
        ),
    ]
