# Generated by Django 5.1.1 on 2024-10-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbis', '0002_person_unique_id_remove_person_notable_offspring_and_more'),
        ('rabbis', '0002_remove_person_notable_offspring_remove_person_wife_and_more'),
    ]

    operations = [
    ]
